# Artificial Neural Network

#### Data Preprocessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:,13].values

In [4]:
X,y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0], dtype=int64))

In [5]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
X = X.astype(np.float64)
X = X[:, 1:]

In [6]:
X, y

(array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
         1.0000000e+00, 1.0134888e+05],
        [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
         1.0000000e+00, 1.1254258e+05],
        [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
         0.0000000e+00, 1.1393157e+05],
        ...,
        [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
         1.0000000e+00, 4.2085580e+04],
        [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
         0.0000000e+00, 9.2888520e+04],
        [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
         0.0000000e+00, 3.8190780e+04]]),
 array([1, 0, 1, ..., 1, 1, 0], dtype=int64))

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [8]:
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Using TensorFlow backend.


#### Initialising the ANN

In [9]:
classifier = Sequential()

#### Adding the input layer and the first hidder layer

In [10]:
classifier.add(Dense(units = 6, activation = 'relu'))

#### Adding the second hidden layer

In [11]:
classifier.add(Dense(units = 6, activation = 'relu'))

#### Adding the output layer

In [12]:
classifier.add(Dense(units = 1,activation = 'sigmoid'))

#### Compiling the ANN

In [13]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

#### Fit the ANN to training set

In [14]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
750/750 [==============================] - 1s 1ms/step - loss: 0.4844 - accuracy: 0.7959
Epoch 2/100
750/750 [==============================] - 1s 1ms/step - loss: 0.4411 - accuracy: 0.7963
Epoch 3/100
750/750 [==============================] - 1s 1ms/step - loss: 0.4326 - accuracy: 0.7963
Epoch 4/100
750/750 [==============================] - 1s 1ms/step - loss: 0.4275 - accuracy: 0.7963
Epoch 5/100
750/750 [==============================] - 1s 2ms/step - loss: 0.4222 - accuracy: 0.8027
Epoch 6/100
750/750 [==============================] - 1s 2ms/step - loss: 0.4148 - accuracy: 0.8177
Epoch 7/100
750/750 [==============================] - 1s 1ms/step - loss: 0.4054 - accuracy: 0.8260
Epoch 8/100
750/750 [==============================] - 1s 1ms/step - loss: 0.3912 - accuracy: 0.8356
Epoch 9/100
750/750 [==============================] - 1s 2ms/step - loss: 0.3772 - accuracy: 0.8433
Epoch 10/100
750/750 [==============================] - 1s 1ms/step - loss: 0.3670 - accura

observing the accuracies above, we can see that the final accuracy will be around 86%

In [15]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1872,  119],
       [ 234,  275]], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score
print('Accuracy of the model is',accuracy_score(y_test, y_pred)*100,'%')

Accuracy of the model is 85.88 %
